<?php
/**
 * Market plugin for Craft Commerce
 *
 * A fully-stocked multi-vendor solution for Craft Commerce.
 *
 * @link      https://angell.io
 * @copyright Copyright (c) 2020 Angell & Co
 */

/**
 * Market en Translation
 *
 * Returns an array with the string to be translated (as passed to `Craft::t('market', '...')`) as
 * the key, and the translation as the value.
 *
 * http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html
 *
 * @author    Angell & Co
 * @package   Market
 * @since     2.0.0
 */
return [
    'Market' => 'Market',
    'Vendor' => 'Vendor',
    'Vendors' => 'Vendors',
    'Active' => 'Active',
    'Pending' => 'Pending',
    'Suspended' => 'Suspended',
    'Profile Picture' => 'Profile Picture',
    'Code' => 'Code',
    'Add a vendor' => 'Add a vendor',
    'Vendor Fields' => 'Vendor Fields',
    'General' => 'General',
    'Vendor Settings' => 'Vendor Settings',
    'Market Settings' => 'Market Settings',
    'Vendor Settings ({siteName})' => 'Vendor Settings ({siteName})',
    'Couldn’t save Vendor settings.' => 'Couldn’t save Vendor settings.',
    'Vendor settings saved.' => 'Vendor settings saved.',
    'What the vendor URLs should look like. You can include tags that output vendor properties, such as {ex1} or {ex2}.' => 'What the vendor URLs should look like. You can include tags that output vendor properties, such as {ex1} or {ex2}.',
    'The template to use when a vendor’s URL is requested.' => 'The template to use when a vendor’s URL is requested.',
    'The asset volume that should used to store this vendor’s files.' => 'The asset volume that should used to store this vendor’s files.',
    'Default Shipping Origin' => 'Default Shipping Origin',
    'Where Vendors will ship from by default, they won’t be able to change this in their shipping profiles but admins can in the cp.' => 'Where Vendors will ship from by default, they won’t be able to change this in their shipping profiles but admins can in the cp.',
    'Client ID' => 'Client ID',
    'A unique identifier for your platform, generated by Stripe. This can be found from your {platform_settings_link}.' => 'A unique identifier for your platform, generated by Stripe. This can be found from your {platform_settings_link}.',
    'Secret Key' => 'Secret Key',
    'Publishable Key' => 'Publishable Key',
    'This can be found in your {api_settings_link}.' => 'This can be found in your {api_settings_link}.',
    'Redirect URI (success)' => 'Redirect URI (success)',
    'A URI to redirect to when a user has successfully connected to Stripe via OAuth.' => 'A URI to redirect to when a user has successfully connected to Stripe via OAuth.',
    'Redirect URI (error)' => 'Redirect URI (error)',
    'A URI to redirect to when there was a problem connecting to Stripe via OAuth.' => 'A URI to redirect to when there was a problem connecting to Stripe via OAuth.',
    'Stripe' => 'Stripe',
    'Stripe Settings ({siteName})' => 'Stripe Settings ({siteName})',
    'Couldn’t save Stripe settings.' => 'Couldn’t save Stripe settings.',
    'Stripe settings saved.' => 'Stripe settings saved.',
    'Vendor Dashboard Title' => 'Vendor Dashboard Title',
    'The title used in the vendor dashboard, defaults to ‘Marketplace’.' => 'The title used in the vendor dashboard, defaults to ‘Marketplace’.',
    'Apply To Sell URL' => 'Apply To Sell URL',
    'If you have a URL where people can apply to sell on your platform, add it here.' => 'If you have a URL where people can apply to sell on your platform, add it here.',
    'Order confirmation email' => 'Order confirmation email',
    'Specify the path of the template you want to use for order confirmation emails.' => 'Specify the path of the template you want to use for order confirmation emails.',
    'Google Analytics UA' => 'Google Analytics UA',
    'If you set this then Google Analytics will be implemented across the marketplace templates.' => 'If you set this then Google Analytics will be implemented across the marketplace templates.',
];
